# -*- coding: utf-8 -*-
"""Heart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KBdAyTkXdLLk2gQI_XwOC0I-ZbCI086U
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

df=pd.read_csv('heart.csv')

df.head()

from sklearn.model_selection import train_test_split
from sklearn import metrics

X=df[["age","sex","chol"]]
Y=df['target']
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.23,random_state=2)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

model.score(x_test,y_test)

# Saving model to disk
pickle.dump(model, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))

